package com.dndmaster.combatmap;
import static org.junit.jupiter.api.Assertions.*;
import com.dndmaster.combatmap.api.PlayerCombatMapResponse; import com.dndmaster.combatmap.application.view.*; import com.dndmaster.combatmap.domain.*; import com.dndmaster.combatmap.infrastructure.persistence.PostgresCombatMapViewStore; import java.sql.*; import java.util.*; import javax.sql.DataSource; import org.flywaydb.core.Flyway; import org.junit.jupiter.api.*; import org.testcontainers.containers.PostgreSQLContainer;
class CombatMapVisibilityIntegrationTest{
 static final PostgreSQLContainer<?> PG=new PostgreSQLContainer<>("postgres:16-alpine").withDatabaseName("combat_map").withUsername("combat_map").withPassword("combat_map"); static DataSource ds; PostgresCombatMapViewStore store; MapOwnerId owner;
 @BeforeAll static void start(){PG.start();ds=new DriverManagerDataSource(PG.getJdbcUrl(),PG.getUsername(),PG.getPassword());Flyway.configure().dataSource(ds).load().migrate();}
 @AfterAll static void stop(){PG.stop();}
 @BeforeEach void reset()throws Exception{try(Connection c=ds.getConnection();Statement s=c.createStatement()){s.execute("TRUNCATE combat_map CASCADE");}store=new PostgresCombatMapViewStore(ds);owner=new MapOwnerId(UUID.randomUUID());}
 @Test void uploadedAndAiGeneratedMapsRestoreFromDatabase(){PreparedMapData data=data();CombatMapViewService service=new CombatMapViewService(store,source->data,description->data);CombatMap uploaded=service.prepareUploaded(owner,adventure(),rules(),new UploadedMapSource("map.png",new byte[]{1}));CombatMap generated=service.prepareGenerated(owner,adventure(),rules(),"dungeon");assertEquals(data.grid(),store.find(uploaded.id()).orElseThrow().map().grid());assertEquals(2,store.find(generated.id()).orElseThrow().map().tokens().size());}
 @Test void adventureProjectionUsesPersistedActiveStageMapInsteadOfMostRecentlyUpdatedMap() throws Exception {PreparedMapData data=data();CombatMapViewService service=service(data);AdventureId adventure=adventure();CombatMap stageOne=service.prepareGenerated(owner,adventure,rules(),"stage-one");CombatMap stageTwo=service.prepareGenerated(owner,adventure,rules(),"stage-two");try(Connection c=ds.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO adventure_active_tactical_map(adventure_id,stage_position,owner_player_id,combat_map_id,active) VALUES (?,?,?,?,true)")){p.setObject(1,adventure.value());p.setInt(2,1);p.setObject(3,owner.value());p.setObject(4,stageOne.id().value());p.executeUpdate();}assertEquals(stageOne.id(),service.displayForAdventure(adventure,owner).orElseThrow().mapId());assertNotEquals(stageTwo.id(),service.displayForAdventure(adventure,owner).orElseThrow().mapId());assertEquals(stageTwo.id(),service.preparedMapIdForAdventure(adventure,owner).orElseThrow());}
 @Test void activatingPreparedMapMakesItVisibleThroughAdventureProjection(){PreparedMapData data=data();CombatMapViewService service=service(data);AdventureId adventure=adventure();CombatMap map=service.prepareGenerated(owner,adventure,rules(),"opening");service.activateForAdventure(map.id(),owner,1);assertEquals(map.id(),service.displayForAdventure(adventure,owner).orElseThrow().mapId());}
 @Test void unactivatedDraftIsReturnedForPreparationAndDisappearsAfterActivation(){PreparedMapData data=data();CombatMapViewService service=service(data);AdventureId adventure=adventure();CombatMap map=service.prepareGenerated(owner,adventure,rules(),"opening");assertEquals(Optional.of(map.id()),service.preparedMapIdForAdventure(adventure,owner));assertEquals(map.id(),service.displayForPreparation(adventure,owner).orElseThrow().mapId());service.activateForAdventure(map.id(),owner,1);assertTrue(service.preparedMapIdForAdventure(adventure,owner).isEmpty());}
 @Test void preparationProjectionDoesNotExposeAPlayerStartCandidate(){
  AdventureId adventure=adventure();
  CombatMapViewService service=service(new PreparedMapData(new GridSpec(4,4,50,5),List.of(
          new CombatToken(new TokenId(UUID.randomUUID()),TokenType.PLAYER,new GridPosition(1,1),TokenController.PLAYER,new PlayerId(owner.value())),
          new CombatToken(new TokenId(UUID.randomUUID()),TokenType.ENEMY,new GridPosition(2,2),TokenController.AI_GAME_MASTER,null)),Set.of(),List.of()));
  CombatMap map=service.prepareGenerated(owner,adventure,rules(),"opening");

  PlayerCombatMapView preparation=service.displayForPreparation(adventure,owner).orElseThrow();

  assertTrue(preparation.tokens().stream().noneMatch(token -> token.type()==TokenType.PLAYER));
  assertTrue(preparation.tokens().stream().anyMatch(token -> token.type()==TokenType.ENEMY));
 }
 @Test void activationResolvesSpawnAndInitialVisibilityAtomically(){AdventureId adventure=adventure();CombatMapViewService service=service(new PreparedMapData(new GridSpec(4,4,50,5),List.of(),Set.of(new GridPosition(1,0)),List.of()));CombatMap map=service.prepareGenerated(owner,adventure,rules(),"opening");CombatMap activated=service.activateForAdventure(map.id(),owner,new MapActivationContext(1,Optional.of(new GridPosition(1,0)),Optional.of(MapActivationContext.EntrySide.NORTH)));assertEquals(new GridPosition(2,0),activated.tokens().stream().filter(t->t.type()==TokenType.PLAYER).findFirst().orElseThrow().position());assertEquals(1,activated.version());assertNotNull(store.find(map.id()).orElseThrow().map().visibilitySnapshot());assertEquals(map.id(),service.displayForAdventure(adventure,owner).orElseThrow().mapId());}
 @Test void draftDoesNotTurnAiSuggestedStartIntoPlayerUntilSituationActivation(){
  AdventureId adventure=adventure();
  PreparedMapData aiDraft=new PreparedMapData(new GridSpec(10,10,50,5),List.of(),Set.of(),
          List.of(new MapLayer("GM_PLAYER_START","1,1",LayerVisibility.AI_ONLY)));
  CombatMapViewService service=service(aiDraft);
  MapGenerationRequest request=new MapGenerationRequest("opening", "scene=opening;location=east gate", 10,10,50,5,List.of(),List.of(),null,null);
  CombatMap draft=service.prepareGenerated(owner,adventure,rules(),request,false);
  assertTrue(draft.tokens().stream().noneMatch(token -> token.type()==TokenType.PLAYER));
  CombatMap activated=service.activateForAdventure(draft.id(),owner,MapActivationContext.from(1,Optional.empty(),Optional.of(MapActivationContext.EntrySide.EAST),Optional.empty(),UUID.randomUUID(),1,0,"opening","east gate"));
  assertEquals(new GridPosition(9,5),activated.tokens().stream().filter(token -> token.type()==TokenType.PLAYER).findFirst().orElseThrow().position());
 }
 @Test void legacyDraftPlayerTokenCannotOverrideSituationEntrySide(){
  AdventureId adventure=adventure();
  PreparedMapData aiDraft=new PreparedMapData(new GridSpec(10,10,50,5),List.of(new CombatToken(new TokenId(UUID.randomUUID()),TokenType.PLAYER,new GridPosition(1,1),TokenController.PLAYER,new PlayerId(owner.value()))),Set.of(),List.of());
  CombatMapViewService service=service(aiDraft);
  CombatMap draft=service.prepareGenerated(owner,adventure,rules(),new MapGenerationRequest("opening","scene=cellar;location=지하 맥주 저장고",10,10,50,5,List.of(),List.of()),true);
  CombatMap activated=service.activateForAdventure(draft.id(),owner,MapActivationContext.from(1,Optional.empty(),Optional.of(MapActivationContext.EntrySide.NORTH),Optional.empty(),UUID.randomUUID(),1,0,"거대 쥐가 드러난 지하 맥주 저장고","지하 맥주 저장고"));
  assertEquals(new GridPosition(5,0),activated.tokens().stream().filter(token -> token.type()==TokenType.PLAYER).findFirst().orElseThrow().position());
 }
 @Test void activationAndVisibilityStayInsideTheReviewedCrop(){
  AdventureId adventure=adventure();
  PreparedMapData draftData=new PreparedMapData(new GridSpec(20,20,10,5),List.of(),Set.of(),List.of(
          new MapLayer("GRID_BOUNDS","0,0,200,200,200,200",LayerVisibility.PLAYER_VISIBLE),
          new MapLayer("MAP_CROP","50,50,100,100",LayerVisibility.PLAYER_VISIBLE)));
  CombatMapViewService service=service(draftData);
  CombatMap draft=service.prepareGenerated(owner,adventure,rules(),"opening");
  CombatMap activated=service.activateForAdventure(draft.id(),owner,MapActivationContext.from(1,Optional.empty(),Optional.of(MapActivationContext.EntrySide.NORTH),Optional.empty(),UUID.randomUUID(),1,0,"cellar","cellar"));
  assertEquals(new GridPosition(10,5),activated.tokens().stream().filter(token -> token.type()==TokenType.PLAYER).findFirst().orElseThrow().position());
  assertTrue(activated.visibilitySnapshot().current().stream().allMatch(position -> position.x() >= 5 && position.x() <= 14 && position.y() >= 5 && position.y() <= 14));
 }
 @Test void activationRejectsVersionConflictAndDoesNotCreateActiveRelation(){AdventureId adventure=adventure();CombatMapViewService service=service(new PreparedMapData(new GridSpec(2,2,50,5),List.of(),Set.of(),List.of()));CombatMap map=service.prepareGenerated(owner,adventure,rules(),"opening");assertThrows(RuntimeException.class,()->store.activate(owner,map,1,1,UUID.randomUUID(),"stale"));assertTrue(service.displayForAdventure(adventure,owner).isEmpty());assertEquals(0,store.find(map.id()).orElseThrow().version());}
 @Test void activationReturnsNoValidPlayerSpawnWithoutPartialState(){AdventureId adventure=adventure();Set<GridPosition> blocked=Set.of(new GridPosition(0,0),new GridPosition(1,0),new GridPosition(0,1),new GridPosition(1,1));CombatMapViewService service=service(new PreparedMapData(new GridSpec(2,2,50,5),List.of(),blocked,List.of()));CombatMap map=service.prepareGenerated(owner,adventure,rules(),"opening");assertThrows(NoValidPlayerSpawnException.class,()->service.activateForAdventure(map.id(),owner,MapActivationContext.atStage(1)));assertTrue(service.displayForAdventure(adventure,owner).isEmpty());assertEquals(0,store.find(map.id()).orElseThrow().version());}
 @Test void adventureProjectionScopesActiveMapSelectionToRequestingOwnerBeforeSelecting() throws Exception {PreparedMapData data=data();CombatMapViewService service=service(data);AdventureId adventure=adventure();MapOwnerId other=new MapOwnerId(UUID.randomUUID());CombatMap own=service.prepareGenerated(owner,adventure,rules(),"own");CombatMap foreign=service.prepareGenerated(other,adventure,rules(),"foreign");try(Connection c=ds.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO adventure_active_tactical_map(adventure_id,stage_position,owner_player_id,combat_map_id,active) VALUES (?,?,?,?,true)")){p.setObject(1,adventure.value());p.setInt(2,1);p.setObject(3,other.value());p.setObject(4,foreign.id().value());p.executeUpdate();p.setInt(2,1);p.setObject(3,owner.value());p.setObject(4,own.id().value());p.executeUpdate();}assertEquals(own.id(),service.displayForAdventure(adventure,owner).orElseThrow().mapId());}
 @Test void playerProjectionNeverExposesAiOnlyLayerAndRejectsOtherOwner(){CombatMapViewService service=service(data());CombatMap map=service.prepareGenerated(owner,adventure(),rules(),"cave");PlayerCombatMapResponse response=PlayerCombatMapResponse.from(service.displayForPlayer(map.id(),owner));assertEquals(List.of("FLOOR"),response.layers().stream().map(PlayerCombatMapResponse.LayerResponse::type).toList());assertThrows(CombatMapAccessDeniedException.class,()->service.displayForPlayer(map.id(),new MapOwnerId(UUID.randomUUID())));}
 @Test void playerProjectionNeverReturnsTheOriginalMapImageLayer(){PreparedMapData prepared=new PreparedMapData(new GridSpec(2,2,2,5),List.of(new CombatToken(new TokenId(UUID.randomUUID()),TokenType.PLAYER,new GridPosition(0,0),TokenController.PLAYER,new PlayerId(owner.value()))),Set.of(),List.of(new MapLayer("MAP_IMAGE",MapImageTestFixture.dataUri(4,4),LayerVisibility.PLAYER_VISIBLE)));CombatMapViewService service=service(prepared);CombatMap map=service.prepareGenerated(owner,adventure(),rules(),"cave");assertTrue(service.displayForPlayer(map.id(),owner).layers().stream().noneMatch(layer->layer.type().equals("MAP_IMAGE")));}
 @Test void missingVisibilitySnapshotProjectsOnlyPlayerOrigin(){CombatMapViewService service=service(data()); PreparedMapData prepared=data(); CombatMap map=new CombatMap(new MapId(UUID.randomUUID()),adventure(),rules(),prepared.grid(),owner.value()==null?null:new PlayerId(owner.value()),prepared.tokens(),prepared.obstacles(),prepared.layers(),0,null); store.insert(owner,map); PlayerCombatMapView view=service.displayForPlayer(map.id(),owner); assertEquals(Set.of(new GridPosition(1,1)),view.current()); assertTrue(view.tokens().stream().allMatch(token -> token.type()==TokenType.PLAYER));}
 @Test void playerProjectionOmitsTokenAndObstacleOutsideExploredCells(){CombatMapViewService service=service(data());CombatMap map=service.prepareGenerated(owner,adventure(),rules(),"cave");PlayerCombatMapResponse response=PlayerCombatMapResponse.from(service.displayForPlayer(map.id(),owner));assertTrue(response.tokens().stream().anyMatch(token -> token.type().equals("PLAYER")));assertTrue(response.tokens().stream().noneMatch(token -> token.type().equals("ENEMY")));assertTrue(response.obstacles().stream().noneMatch(obstacle -> obstacle.x()==9&&obstacle.y()==9));CombatMap restored=store.find(map.id()).orElseThrow().map();assertNotNull(restored.visibilitySnapshot());assertTrue(restored.visibilitySnapshot().explored().contains(new GridPosition(3,3)));}
 @Test void playerProjectionHidesVisibleTokenAndLastSeenInsideInitialFog(){PreparedMapData fogged=new PreparedMapData(new GridSpec(10,10,50,5),List.of(new CombatToken(new TokenId(UUID.randomUUID()),TokenType.PLAYER,new GridPosition(1,1),TokenController.PLAYER,new PlayerId(owner.value())),new CombatToken(new TokenId(UUID.randomUUID()),TokenType.ENEMY,new GridPosition(2,1),TokenController.AI_GAME_MASTER,null)),Set.of(),List.of(new MapLayer("INITIAL_FOG","2,1",LayerVisibility.AI_ONLY)));CombatMapViewService service=service(fogged);CombatMap map=service.prepareGenerated(owner,adventure(),rules(),"fog");PlayerCombatMapView view=service.displayForPlayer(map.id(),owner);assertTrue(view.tokens().stream().noneMatch(token -> token.type()==TokenType.ENEMY));assertTrue(view.lastSeenTokens().isEmpty());assertTrue(service.displayForGm(map.id(),owner).tokens().stream().anyMatch(token -> token.type()==TokenType.ENEMY));}
 @Test void gameTimeRejectsForeignOrRewoundEventsAndReplaysSameCommand(){CombatMapViewService service=service(data());AdventureId adventure=adventure();CombatMap map=service.prepareGenerated(owner,adventure,rules(),"cave");UUID cause=UUID.randomUUID();service.onGameTimeAdvanced(map.id(),owner,0,new GameTimeAdvanced(adventure.value(),2,cause));assertEquals(map.id(),service.onGameTimeAdvanced(map.id(),owner,1,new GameTimeAdvanced(adventure.value(),2,cause)).id());assertThrows(IllegalArgumentException.class,()->service.onGameTimeAdvanced(map.id(),owner,1,new GameTimeAdvanced(UUID.randomUUID(),3,UUID.randomUUID())));assertThrows(IllegalArgumentException.class,()->service.onGameTimeAdvanced(map.id(),owner,1,new GameTimeAdvanced(adventure.value(),1,UUID.randomUUID())));}
 @Test void aiControlsOnlyAiTokenAndAiLayersWithOptimisticVersion(){PreparedMapData data=data();CombatMapViewService service=service(data);CombatMap map=service.prepareGenerated(owner,adventure(),rules(),"arena");CombatToken enemy=map.tokens().stream().filter(t->t.type()==TokenType.ENEMY).findFirst().orElseThrow();UUID commandId=UUID.randomUUID();CombatMap updated=service.controlAiState(map.id(),owner,0,commandId,enemy.id(),new GridPosition(6,6),List.of(new MapLayer("FOG","secret",LayerVisibility.AI_ONLY)));assertEquals(new GridPosition(6,6),updated.tokens().stream().filter(t->t.id().equals(enemy.id())).findFirst().orElseThrow().position());assertEquals(List.of("FLOOR"),service.displayForPlayer(map.id(),owner).layers().stream().map(MapLayer::type).toList());assertThrows(IllegalStateException.class,()->service.controlAiState(map.id(),owner,0,UUID.randomUUID(),enemy.id(),new GridPosition(7,7),List.of()));CombatToken player=map.tokens().stream().filter(t->t.type()==TokenType.PLAYER).findFirst().orElseThrow();assertThrows(CombatMapAccessDeniedException.class,()->service.controlAiState(map.id(),owner,1,UUID.randomUUID(),player.id(),new GridPosition(2,2),List.of()));}
 @Test void persistsLatestCommandMetadataWhenAiControlUpdatesTheMap(){PreparedMapData data=data();CombatMapViewService service=service(data);CombatMap map=service.prepareGenerated(owner,adventure(),rules(),"arena");CombatToken enemy=map.tokens().stream().filter(t->t.type()==TokenType.ENEMY).findFirst().orElseThrow();UUID commandId=UUID.randomUUID();GridPosition position=new GridPosition(6,6);List<MapLayer> layers=List.of(new MapLayer("FOG","secret",LayerVisibility.AI_ONLY));service.controlAiState(map.id(),owner,0,commandId,enemy.id(),position,layers);CombatMap restored=store.find(map.id()).orElseThrow().map();assertEquals(commandId,restored.operationKey());assertEquals(commandId+"|"+owner+"|"+enemy.id()+"|"+position+"|"+layers,restored.operationFingerprint());assertEquals(1L,restored.version());}
 @Test void replays_an_older_ai_command_from_history_even_after_a_later_update(){PreparedMapData data=data();CombatMapViewService service=service(data);CombatMap map=service.prepareGenerated(owner,adventure(),rules(),"arena");CombatToken enemy=map.tokens().stream().filter(t->t.type()==TokenType.ENEMY).findFirst().orElseThrow();UUID firstCommandId=UUID.randomUUID();GridPosition firstPosition=new GridPosition(6,6);List<MapLayer> firstLayers=List.of(new MapLayer("FOG","secret",LayerVisibility.AI_ONLY));CombatMap first=service.controlAiState(map.id(),owner,0,firstCommandId,enemy.id(),firstPosition,firstLayers);service.controlAiState(map.id(),owner,1,UUID.randomUUID(),enemy.id(),new GridPosition(7,7),List.of());CombatMap replay=service.controlAiState(map.id(),owner,1,firstCommandId,enemy.id(),firstPosition,firstLayers);assertEquals(new GridPosition(6,6),first.tokens().stream().filter(t->t.id().equals(enemy.id())).findFirst().orElseThrow().position());assertEquals(new GridPosition(6,6),replay.tokens().stream().filter(t->t.id().equals(enemy.id())).findFirst().orElseThrow().position());assertNotNull(replay.visibilitySnapshot());assertEquals(1L,replay.version());assertEquals(firstCommandId,replay.operationKey());}
 @Test void fileAndAiPortFailuresNeverPersistMap()throws Exception{CombatMapViewService fileFailure=new CombatMapViewService(store,source->{throw new IllegalStateException("file failure");},description->data());assertThrows(IllegalStateException.class,()->fileFailure.prepareUploaded(owner,adventure(),rules(),new UploadedMapSource("bad",new byte[]{1})));CombatMapViewService aiFailure=new CombatMapViewService(store,source->data(),description->{throw new IllegalStateException("AI failure");});assertThrows(IllegalStateException.class,()->aiFailure.prepareGenerated(owner,adventure(),rules(),"bad"));try(Connection c=ds.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT count(*) FROM combat_map")){r.next();assertEquals(0,r.getInt(1));}}
 private CombatMapViewService service(PreparedMapData data){return new CombatMapViewService(store,source->data,description->data);}
 private static PreparedMapData data(){PlayerId player=new PlayerId(UUID.randomUUID());return new PreparedMapData(new GridSpec(10,10,50,5),List.of(new CombatToken(new TokenId(UUID.randomUUID()),TokenType.PLAYER,new GridPosition(1,1),TokenController.PLAYER,player),new CombatToken(new TokenId(UUID.randomUUID()),TokenType.ENEMY,new GridPosition(4,4),TokenController.AI_GAME_MASTER,null)),Set.of(new GridPosition(3,3),new GridPosition(9,9)),List.of(new MapLayer("FLOOR","stone",LayerVisibility.PLAYER_VISIBLE),new MapLayer("SECRET","door",LayerVisibility.AI_ONLY)));}
 private static AdventureId adventure(){return new AdventureId(UUID.randomUUID());}private static RuleSetId rules(){return new RuleSetId(UUID.randomUUID());}
 private record DriverManagerDataSource(String url,String user,String pass)implements DataSource{public Connection getConnection()throws SQLException{return DriverManager.getConnection(url,user,pass);}public Connection getConnection(String u,String p)throws SQLException{return DriverManager.getConnection(url,u,p);}public<T>T unwrap(Class<T>c)throws SQLException{throw new SQLException();}public boolean isWrapperFor(Class<?>c){return false;}public java.io.PrintWriter getLogWriter(){return null;}public void setLogWriter(java.io.PrintWriter out){}public void setLoginTimeout(int s){}public int getLoginTimeout(){return 0;}public java.util.logging.Logger getParentLogger(){return java.util.logging.Logger.getGlobal();}}
}
