package com.dndmaster.combatmap.infrastructure.persistence;
import com.dndmaster.combatmap.application.view.*; import com.dndmaster.combatmap.domain.*; import java.sql.*; import java.util.*; import javax.sql.DataSource;
public final class PostgresCombatMapViewStore implements CombatMapViewStore{
 private final DataSource ds;public PostgresCombatMapViewStore(DataSource ds){this.ds=Objects.requireNonNull(ds);}
 public void insert(MapOwnerId owner,CombatMap map){write(owner,map,-1,true);}
 public long update(MapOwnerId owner,CombatMap map,long expected){write(owner,map,expected,false);return expected+1;}
 private void write(MapOwnerId owner,CombatMap map,long expected,boolean insert){try(Connection c=ds.getConnection()){c.setAutoCommit(false);try{if(insert)insertMap(c,owner,map);else updateMap(c,owner,map,expected);replace(c,map);c.commit();}catch(SQLException|RuntimeException e){c.rollback();if(e instanceof OptimisticCombatMapLockException o)throw o;throw new CombatMapPersistenceException("map save failed",e);}}catch(SQLException e){throw new CombatMapPersistenceException("map DB failed",e);}}
 private static void insertMap(Connection c,MapOwnerId owner,CombatMap m)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO combat_map VALUES (?,?,?,?,?,?,?,?,0)")){s.setObject(1,m.id().value());s.setObject(2,owner.value());s.setObject(3,m.adventureId().value());s.setObject(4,m.ruleSetId().value());s.setInt(5,m.grid().width());s.setInt(6,m.grid().height());s.setInt(7,m.grid().cellSize());s.setInt(8,m.grid().distanceUnit());s.executeUpdate();}}
 private static void updateMap(Connection c,MapOwnerId owner,CombatMap m,long v)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE combat_map SET grid_width=?,grid_height=?,cell_size=?,distance_unit=?,version=version+1 WHERE map_id=? AND owner_player_id=? AND version=?")){s.setInt(1,m.grid().width());s.setInt(2,m.grid().height());s.setInt(3,m.grid().cellSize());s.setInt(4,m.grid().distanceUnit());s.setObject(5,m.id().value());s.setObject(6,owner.value());s.setLong(7,v);if(s.executeUpdate()!=1)throw new OptimisticCombatMapLockException();}}
 private static void replace(Connection c,CombatMap m)throws SQLException{for(String t:List.of("combat_map_token","combat_map_obstacle","combat_map_layer"))try(PreparedStatement s=c.prepareStatement("DELETE FROM "+t+" WHERE map_id=?")){s.setObject(1,m.id().value());s.executeUpdate();}try(PreparedStatement s=c.prepareStatement("INSERT INTO combat_map_token VALUES (?,?,?,?,?,?,?)")){for(CombatToken t:m.tokens()){s.setObject(1,m.id().value());s.setObject(2,t.id().value());s.setString(3,t.type().name());s.setInt(4,t.position().x());s.setInt(5,t.position().y());s.setString(6,t.controller().name());s.setObject(7,t.ownerPlayerId().map(PlayerId::value).orElse(null));s.addBatch();}s.executeBatch();}try(PreparedStatement s=c.prepareStatement("INSERT INTO combat_map_obstacle VALUES (?,?,?)")){for(GridPosition p:m.obstacles()){s.setObject(1,m.id().value());s.setInt(2,p.x());s.setInt(3,p.y());s.addBatch();}s.executeBatch();}try(PreparedStatement s=c.prepareStatement("INSERT INTO combat_map_layer(map_id,sequence,layer_type,layer_value,visibility) VALUES (?,?,?,?,?)")){for(int i=0;i<m.layers().size();i++){MapLayer l=m.layers().get(i);s.setObject(1,m.id().value());s.setInt(2,i);s.setString(3,l.type());s.setString(4,l.value());s.setString(5,l.visibility().name());s.addBatch();}s.executeBatch();}}
 public Optional<VersionedOwnedCombatMap> find(MapId id){try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement("SELECT * FROM combat_map WHERE map_id=?")){s.setObject(1,id.value());try(ResultSet r=s.executeQuery()){if(!r.next())return Optional.empty();GridSpec g=new GridSpec(r.getInt("grid_width"),r.getInt("grid_height"),r.getInt("cell_size"),r.getInt("distance_unit"));List<CombatToken> tokens=new ArrayList<>();try(PreparedStatement q=c.prepareStatement("SELECT * FROM combat_map_token WHERE map_id=? ORDER BY token_id")){q.setObject(1,id.value());try(ResultSet x=q.executeQuery()){while(x.next())tokens.add(new CombatToken(new TokenId(x.getObject("token_id",UUID.class)),TokenType.valueOf(x.getString("token_type")),new GridPosition(x.getInt("x"),x.getInt("y")),TokenController.valueOf(x.getString("controller")),x.getObject("owner_player_id")==null?null:new PlayerId(x.getObject("owner_player_id",UUID.class))));}}Set<GridPosition> obstacles=new HashSet<>();try(PreparedStatement q=c.prepareStatement("SELECT x,y FROM combat_map_obstacle WHERE map_id=?")){q.setObject(1,id.value());try(ResultSet x=q.executeQuery()){while(x.next())obstacles.add(new GridPosition(x.getInt(1),x.getInt(2)));}}List<MapLayer> layers=new ArrayList<>();try(PreparedStatement q=c.prepareStatement("SELECT * FROM combat_map_layer WHERE map_id=? ORDER BY sequence")){q.setObject(1,id.value());try(ResultSet x=q.executeQuery()){while(x.next())layers.add(new MapLayer(x.getString("layer_type"),x.getString("layer_value"),LayerVisibility.valueOf(x.getString("visibility"))));}}CombatMap map=new CombatMap(id,new AdventureId(r.getObject("adventure_id",UUID.class)),new RuleSetId(r.getObject("rule_set_id",UUID.class)),g,tokens,obstacles,layers);return Optional.of(new VersionedOwnedCombatMap(map,new MapOwnerId(r.getObject("owner_player_id",UUID.class)),r.getLong("version")));}}catch(SQLException e){throw new CombatMapPersistenceException("map load failed",e);}}
}
