package com.dndmaster.aigamemaster;
import static com.github.tomakehurst.wiremock.client.WireMock.*;import static com.github.tomakehurst.wiremock.stubbing.Scenario.STARTED;import static org.junit.jupiter.api.Assertions.*;
import com.dndmaster.aigamemaster.infrastructure.ai.*;import com.github.tomakehurst.wiremock.WireMockServer;import com.github.tomakehurst.wiremock.core.WireMockConfiguration;import java.net.URI;import java.net.http.*;import java.time.Duration;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.ai.chat.messages.AssistantMessage;import org.springframework.ai.chat.model.*;import org.springframework.ai.chat.prompt.Prompt;
class AiProviderFailureIntegrationTest{
 WireMockServer server;List<String> logs;
 @BeforeEach void start(){server=new WireMockServer(WireMockConfiguration.options().dynamicPort());server.start();logs=new ArrayList<>();}
 @AfterEach void stop(){if(server!=null)server.stop();}
 @Test void retriesRateLimitThenCachesSameOperationWithoutLoggingRawData(){server.stubFor(post("/chat").inScenario("rate").whenScenarioStateIs(STARTED).willReturn(aResponse().withStatus(429)).willSetStateTo("ok"));server.stubFor(post("/chat").inScenario("rate").whenScenarioStateIs("ok").willReturn(okJson("{\"value\":\"ok\"}")));SpringAiChatAdapter adapter=adapter(Duration.ofSeconds(1),3);String prompt="RAW_RULEBOOK_SECRET private-map";String first=adapter.complete("op-1",prompt,AiProviderFailureIntegrationTest::parseValue);String duplicate=adapter.complete("op-1",prompt,AiProviderFailureIntegrationTest::parseValue);assertEquals("ok",first);assertEquals(first,duplicate);server.verify(2,postRequestedFor(urlEqualTo("/chat")));assertTrue(logs.stream().noneMatch(l->l.contains("RAW_RULEBOOK_SECRET")||l.contains("private-map")||l.contains("{\"value\"")));assertThrows(AiOperationConflictException.class,()->adapter.complete("op-1","different prompt",AiProviderFailureIntegrationTest::parseValue));}
 @Test void retriesTimeoutOnlyToBoundedAttemptCount(){server.stubFor(post("/chat").willReturn(okJson("{\"value\":\"late\"}").withFixedDelay(250)));SpringAiChatAdapter adapter=adapter(Duration.ofMillis(50),2);assertThrows(ProviderTimeoutException.class,()->adapter.complete("timeout","grounded",AiProviderFailureIntegrationTest::parseValue));server.verify(2,postRequestedFor(urlEqualTo("/chat")));}
 @Test void malformedResponseIsNotRetried(){server.stubFor(post("/chat").willReturn(ok("not-json")));SpringAiChatAdapter adapter=adapter(Duration.ofSeconds(1),3);assertThrows(ProviderMalformedResponseException.class,()->adapter.complete("malformed","grounded",AiProviderFailureIntegrationTest::parseValue));server.verify(1,postRequestedFor(urlEqualTo("/chat")));}
 private SpringAiChatAdapter adapter(Duration timeout,int attempts){return new SpringAiChatAdapter(new WireMockChatModel(server.baseUrl(),timeout),attempts,new SafeAiAuditLogger(logs::add));}
 private static String parseValue(String response){if(!response.startsWith("{\"value\":\"")||!response.endsWith("\"}"))throw new ProviderMalformedResponseException("malformed structured response");return response.substring(10,response.length()-2);}
 private static final class WireMockChatModel implements ChatModel{private final URI uri;private final HttpClient client;private final Duration timeout;WireMockChatModel(String baseUrl,Duration timeout){uri=URI.create(baseUrl+"/chat");client=HttpClient.newHttpClient();this.timeout=timeout;}public ChatResponse call(Prompt prompt){try{HttpRequest request=HttpRequest.newBuilder(uri).timeout(timeout).POST(HttpRequest.BodyPublishers.ofString(prompt.getContents())).build();HttpResponse<String> response=client.send(request,HttpResponse.BodyHandlers.ofString());if(response.statusCode()==429)throw new ProviderRateLimitException();return response(response.body());}catch(java.net.http.HttpTimeoutException e){throw new ProviderTimeoutException(e);}catch(java.io.IOException|InterruptedException e){Thread.currentThread().interrupt();throw new RuntimeException(e);}}}
 private static ChatResponse response(String text){return new ChatResponse(List.of(new Generation(new AssistantMessage(text))));}
}
