package com.dndmaster.combatmap.application.view;
import com.dndmaster.combatmap.domain.*; import java.util.*;
public final class CombatMapViewService{
 private final CombatMapViewStore store;private final MapFilePreparationPort filePort;private final AiMapGenerationPort aiPort;
 public CombatMapViewService(CombatMapViewStore store,MapFilePreparationPort filePort,AiMapGenerationPort aiPort){this.store=Objects.requireNonNull(store);this.filePort=Objects.requireNonNull(filePort);this.aiPort=Objects.requireNonNull(aiPort);}
 public CombatMap prepareUploaded(MapOwnerId owner,AdventureId adventure,RuleSetId rules,UploadedMapSource source){return saveNew(owner,adventure,rules,filePort.prepare(source));}
 public CombatMap prepareGenerated(MapOwnerId owner,AdventureId adventure,RuleSetId rules,String description){if(description==null||description.isBlank())throw new IllegalArgumentException("description required");return saveNew(owner,adventure,rules,aiPort.generate(description.trim()));}
 private CombatMap saveNew(MapOwnerId owner,AdventureId adventure,RuleSetId rules,PreparedMapData data){CombatMap map=new CombatMap(new MapId(UUID.randomUUID()),adventure,rules,data.grid(),new PlayerId(owner.value()),data.tokens(),data.obstacles(),data.layers(),0,null);store.insert(owner,map);return map;}
 public CombatMap controlAiState(MapId id,MapOwnerId owner,long expectedVersion,java.util.UUID commandId,TokenId tokenId,GridPosition position,List<MapLayer> aiLayers){VersionedOwnedCombatMap replay=store.findByCommandId(commandId).orElse(null);List<MapLayer> layers;if(replay!=null){String fingerprint=commandId+"|"+owner+"|"+tokenId+"|"+position+"|"+aiLayers;if(!fingerprint.equals(replay.map().operationFingerprint()))throw new IllegalStateException("combat map command id reused with different payload");return replay.map();}VersionedOwnedCombatMap state=owned(id,owner);layers=new ArrayList<>(state.map().layers().stream().filter(l->l.visibility()==LayerVisibility.PLAYER_VISIBLE).toList());layers.addAll(aiLayers);String fingerprint=commandId+"|"+owner+"|"+tokenId+"|"+position+"|"+aiLayers;if(state.version()!=expectedVersion)throw new IllegalStateException("version mismatch");if(aiLayers.stream().anyMatch(l->l.visibility()!=LayerVisibility.AI_ONLY))throw new IllegalArgumentException("AI control accepts only AI_ONLY layers");List<CombatToken> tokens=state.map().tokens().stream().map(t->{if(!t.id().equals(tokenId))return copy(t,t.position());if(t.controller()!=TokenController.AI_GAME_MASTER)throw new CombatMapAccessDeniedException();return copy(t,position);}).toList();if(tokens.stream().noneMatch(t->t.id().equals(tokenId)))throw new CombatMapAccessDeniedException();CombatMap updated=new CombatMap(state.map().id(),state.map().adventureId(),state.map().ruleSetId(),state.map().grid(),state.map().ownerPlayerId(),tokens,state.map().obstacles(),layers,expectedVersion+1,commandId,fingerprint);store.update(owner,updated,expectedVersion);return updated;}
 public PlayerCombatMapView displayForPlayer(MapId id,MapOwnerId owner){VersionedOwnedCombatMap state=owned(id,owner);CombatMap map=state.map();return new PlayerCombatMapView(map.id(),map.grid(),map.tokens(),map.obstacles(),map.layers().stream().filter(l->l.visibility()==LayerVisibility.PLAYER_VISIBLE).toList(),state.version());}
 public Optional<PlayerCombatMapView> displayForAdventure(AdventureId adventureId,MapOwnerId owner){return store.findByAdventureId(adventureId).filter(state -> state.owner().equals(owner)).map(state -> { CombatMap map=state.map(); return new PlayerCombatMapView(map.id(),map.grid(),map.tokens(),map.obstacles(),map.layers().stream().filter(l->l.visibility()==LayerVisibility.PLAYER_VISIBLE).toList(),state.version()); });}
 private VersionedOwnedCombatMap owned(MapId id,MapOwnerId owner){VersionedOwnedCombatMap state=store.find(id).orElseThrow(CombatMapAccessDeniedException::new);if(!state.owner().equals(owner))throw new CombatMapAccessDeniedException();return state;}
 private static CombatToken copy(CombatToken t,GridPosition p){return new CombatToken(t.id(),t.type(),p,t.controller(),t.ownerPlayerId().orElse(null));}
}
