package com.dndmaster.combatmap;
import static org.junit.jupiter.api.Assertions.*;
import com.dndmaster.combatmap.api.PlayerCombatMapResponse; import com.dndmaster.combatmap.application.view.*; import com.dndmaster.combatmap.domain.*; import com.dndmaster.combatmap.infrastructure.persistence.PostgresCombatMapViewStore; import java.sql.*; import java.util.*; import javax.sql.DataSource; import org.flywaydb.core.Flyway; import org.junit.jupiter.api.*; import org.testcontainers.containers.PostgreSQLContainer;
class CombatMapVisibilityIntegrationTest{
 static final PostgreSQLContainer<?> PG=new PostgreSQLContainer<>("postgres:16-alpine").withDatabaseName("combat_map").withUsername("combat_map").withPassword("combat_map"); static DataSource ds; PostgresCombatMapViewStore store; MapOwnerId owner;
 @BeforeAll static void start(){PG.start();ds=new DriverManagerDataSource(PG.getJdbcUrl(),PG.getUsername(),PG.getPassword());Flyway.configure().dataSource(ds).load().migrate();}
 @AfterAll static void stop(){PG.stop();}
 @BeforeEach void reset()throws Exception{try(Connection c=ds.getConnection();Statement s=c.createStatement()){s.execute("TRUNCATE combat_map CASCADE");}store=new PostgresCombatMapViewStore(ds);owner=new MapOwnerId(UUID.randomUUID());}
 @Test void uploadedAndAiGeneratedMapsRestoreFromDatabase(){PreparedMapData data=data();CombatMapViewService service=new CombatMapViewService(store,source->data,description->data);CombatMap uploaded=service.prepareUploaded(owner,adventure(),rules(),new UploadedMapSource("map.png",new byte[]{1}));CombatMap generated=service.prepareGenerated(owner,adventure(),rules(),"dungeon");assertEquals(data.grid(),store.find(uploaded.id()).orElseThrow().map().grid());assertEquals(2,store.find(generated.id()).orElseThrow().map().tokens().size());}
 @Test void playerProjectionNeverExposesAiOnlyLayerAndRejectsOtherOwner(){CombatMapViewService service=service(data());CombatMap map=service.prepareGenerated(owner,adventure(),rules(),"cave");PlayerCombatMapResponse response=PlayerCombatMapResponse.from(service.displayForPlayer(map.id(),owner));assertEquals(List.of("FLOOR"),response.layers().stream().map(PlayerCombatMapResponse.LayerResponse::type).toList());assertThrows(CombatMapAccessDeniedException.class,()->service.displayForPlayer(map.id(),new MapOwnerId(UUID.randomUUID())));}
 @Test void aiControlsOnlyAiTokenAndAiLayersWithOptimisticVersion(){PreparedMapData data=data();CombatMapViewService service=service(data);CombatMap map=service.prepareGenerated(owner,adventure(),rules(),"arena");CombatToken enemy=map.tokens().stream().filter(t->t.type()==TokenType.ENEMY).findFirst().orElseThrow();CombatMap updated=service.controlAiState(map.id(),owner,0,enemy.id(),new GridPosition(6,6),List.of(new MapLayer("FOG","secret",LayerVisibility.AI_ONLY)));assertEquals(new GridPosition(6,6),updated.tokens().stream().filter(t->t.id().equals(enemy.id())).findFirst().orElseThrow().position());assertEquals(List.of("FLOOR"),service.displayForPlayer(map.id(),owner).layers().stream().map(MapLayer::type).toList());assertThrows(IllegalStateException.class,()->service.controlAiState(map.id(),owner,0,enemy.id(),new GridPosition(7,7),List.of()));CombatToken player=map.tokens().stream().filter(t->t.type()==TokenType.PLAYER).findFirst().orElseThrow();assertThrows(CombatMapAccessDeniedException.class,()->service.controlAiState(map.id(),owner,1,player.id(),new GridPosition(2,2),List.of()));}
 @Test void fileAndAiPortFailuresNeverPersistMap()throws Exception{CombatMapViewService fileFailure=new CombatMapViewService(store,source->{throw new IllegalStateException("file failure");},description->data());assertThrows(IllegalStateException.class,()->fileFailure.prepareUploaded(owner,adventure(),rules(),new UploadedMapSource("bad",new byte[]{1})));CombatMapViewService aiFailure=new CombatMapViewService(store,source->data(),description->{throw new IllegalStateException("AI failure");});assertThrows(IllegalStateException.class,()->aiFailure.prepareGenerated(owner,adventure(),rules(),"bad"));try(Connection c=ds.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT count(*) FROM combat_map")){r.next();assertEquals(0,r.getInt(1));}}
 private CombatMapViewService service(PreparedMapData data){return new CombatMapViewService(store,source->data,description->data);}
 private static PreparedMapData data(){PlayerId player=new PlayerId(UUID.randomUUID());return new PreparedMapData(new GridSpec(10,10,50,5),List.of(new CombatToken(new TokenId(UUID.randomUUID()),TokenType.PLAYER,new GridPosition(1,1),TokenController.PLAYER,player),new CombatToken(new TokenId(UUID.randomUUID()),TokenType.ENEMY,new GridPosition(4,4),TokenController.AI_GAME_MASTER,null)),Set.of(new GridPosition(3,3)),List.of(new MapLayer("FLOOR","stone",LayerVisibility.PLAYER_VISIBLE),new MapLayer("SECRET","door",LayerVisibility.AI_ONLY)));}
 private static AdventureId adventure(){return new AdventureId(UUID.randomUUID());}private static RuleSetId rules(){return new RuleSetId(UUID.randomUUID());}
 private record DriverManagerDataSource(String url,String user,String pass)implements DataSource{public Connection getConnection()throws SQLException{return DriverManager.getConnection(url,user,pass);}public Connection getConnection(String u,String p)throws SQLException{return DriverManager.getConnection(url,u,p);}public<T>T unwrap(Class<T>c)throws SQLException{throw new SQLException();}public boolean isWrapperFor(Class<?>c){return false;}public java.io.PrintWriter getLogWriter(){return null;}public void setLogWriter(java.io.PrintWriter out){}public void setLoginTimeout(int s){}public int getLoginTimeout(){return 0;}public java.util.logging.Logger getParentLogger(){return java.util.logging.Logger.getGlobal();}}
}
