package com.dndmaster.combatmap;
import static org.junit.jupiter.api.Assertions.*;
import com.dndmaster.combatmap.application.movement.*; import com.dndmaster.combatmap.domain.*; import java.util.*; import org.junit.jupiter.api.Test;
class CombatMapMovementTest {
    @Test void movesOnlyOwnedPlayerTokenWithinAppliedEditionAllowance(){ Fixture f=new Fixture(); CombatMapMovementService service=f.service(10); MovementPath path=new MovementPath(List.of(new GridPosition(1,1),new GridPosition(2,1),new GridPosition(3,1)),10); service.movePlayerToken(new MovePlayerTokenCommand(f.map.id(),f.player,f.playerToken.id(),path,"D&D 5E 2024")); assertEquals(new GridPosition(3,1),f.playerToken.position()); assertEquals(1,f.saves); }
    @Test void rejectsOtherPlayersAndAiControlledTokens(){ Fixture f=new Fixture(); var path=new MovementPath(List.of(new GridPosition(1,1),new GridPosition(2,1)),5); assertThrows(CombatMapMovementDeniedException.class,()->f.service(30).movePlayerToken(new MovePlayerTokenCommand(f.map.id(),new PlayerId(UUID.randomUUID()),f.playerToken.id(),path,"5E"))); var aiPath=new MovementPath(List.of(new GridPosition(4,4),new GridPosition(5,4)),5); assertThrows(CombatMapMovementDeniedException.class,()->f.service(30).movePlayerToken(new MovePlayerTokenCommand(f.map.id(),f.player,f.enemyToken.id(),aiPath,"5E"))); }
    @Test void rejectsPathBeyondEditionAllowanceOrAcrossObstacle(){ Fixture f=new Fixture(); var tooFar=new MovementPath(List.of(new GridPosition(1,1),new GridPosition(2,1),new GridPosition(3,1)),10); assertThrows(CombatMapMovementDeniedException.class,()->f.service(5).movePlayerToken(new MovePlayerTokenCommand(f.map.id(),f.player,f.playerToken.id(),tooFar,"5E"))); var blocked=new MovementPath(List.of(new GridPosition(1,1),new GridPosition(1,2)),5); assertThrows(CombatMapMovementDeniedException.class,()->f.service(30).movePlayerToken(new MovePlayerTokenCommand(f.map.id(),f.player,f.playerToken.id(),blocked,"5E"))); }
    @Test void enforcesControllerAndLayerVisibilityModel(){ PlayerId player=new PlayerId(UUID.randomUUID()); assertThrows(IllegalArgumentException.class,()->new CombatToken(new TokenId(UUID.randomUUID()),TokenType.PLAYER,new GridPosition(0,0),TokenController.AI_GAME_MASTER,player)); assertThrows(IllegalArgumentException.class,()->new CombatToken(new TokenId(UUID.randomUUID()),TokenType.NPC,new GridPosition(0,0),TokenController.PLAYER,null)); Fixture f=new Fixture(); assertEquals(List.of(LayerVisibility.PLAYER_VISIBLE,LayerVisibility.AI_ONLY),f.map.layers().stream().map(MapLayer::visibility).toList()); }
    private static final class Fixture implements CombatMapRepository {
        final PlayerId player=new PlayerId(UUID.randomUUID()); final CombatToken playerToken=new CombatToken(new TokenId(UUID.randomUUID()),TokenType.PLAYER,new GridPosition(1,1),TokenController.PLAYER,player); final CombatToken enemyToken=new CombatToken(new TokenId(UUID.randomUUID()),TokenType.ENEMY,new GridPosition(4,4),TokenController.AI_GAME_MASTER,null); final CombatMap map=new CombatMap(new MapId(UUID.randomUUID()),new AdventureId(UUID.randomUUID()),new RuleSetId(UUID.randomUUID()),new GridSpec(10,10,50,5),List.of(playerToken,enemyToken),List.of(new GridPosition(1,2)),List.of(new MapLayer("LIGHT","bright",LayerVisibility.PLAYER_VISIBLE),new MapLayer("FOG","hidden",LayerVisibility.AI_ONLY))); int saves;
        CombatMapMovementService service(int allowance){return new CombatMapMovementService(this,(ruleSet,edition)->allowance);} public Optional<CombatMap> findById(MapId id){return id.equals(map.id())?Optional.of(map):Optional.empty();} public void save(CombatMap map){saves++;}
    }
}
