
import { useEffect, useMemo, useState } from 'react'
import type { CharacterCreationDraft, CharacterInputNodeView, SetupApi } from '../rulebooks/SetupApi'
import type { AdventureSessionApi } from '../adventure-session/AdventureSessionApi'
import { backgroundOptions, classOptions, raceOptions } from './Dnd5eCharacterCatalog'

const stats = ['근력', '민첩', '건강', '지능', '지혜', '매력']
const scoreKeys = [['strength', 'str'], ['dexterity', 'dex'], ['constitution', 'con'], ['intelligence', 'int'], ['wisdom', 'wis'], ['charisma', 'cha']]
const art = { 위저드: '/assets/characters/wizard.png', 팔라딘: '/assets/characters/paladin.png', 로그: '/assets/characters/rogue.png' }
type ChoiceOption = { id: string; label: string; description: string; details: string[] }
const raceChoices: ChoiceOption[] = raceOptions.map(race => ({ id: race.id, label: race.label, description: race.description, details: [...race.traits, `언어: ${race.languages.join(', ')}`] }))
function subraceChoicesFor(value: string): ChoiceOption[] {
  const parent = raceOptions.find(race => race.id === value)
  return parent?.subraces.map(subrace => ({ id: subrace.id, label: subrace.label, description: subrace.description, details: [...subrace.traits, `부모 종족: ${parent.label}`] })) ?? []
}
const classChoices: ChoiceOption[] = classOptions.map(option => ({ id: option.id, label: option.label, description: option.description, details: [`생명력 주사위: ${option.hitDie}`, `내성 숙련: ${option.savingThrows.join(', ')}`, `기술 선택: ${option.skillChoiceCount}개`, `클래스 특성: ${option.features.join(', ')}`] }))
const backgroundChoices: ChoiceOption[] = backgroundOptions.map(option => ({ id: option.id, label: option.label, description: option.description, details: [`기술 숙련: ${option.skills.join(', ')}`, `장비: ${option.equipment.join(', ')}`] }))
const alignmentChoices: ChoiceOption[] = [
  ['질서 선', '사회적으로 올바르다고 여기는 행동을 하려고 합니다.'], ['중립 선', '다른 사람들이 도움을 요청할 때 그들을 돕기 위해 최선을 다합니다.'], ['혼돈 선', '다른 사람의 기대나 예상은 신경 쓰지 않고 오로지 자신의 양심에 따라 움직입니다.'],
  ['질서 중립', '법과 전통, 개인의 규범에 따라 행동합니다.'], ['중립', '도덕적 문제에 명확한 태도를 취하지 않고 그때그때 최선이라 생각하는 행동을 합니다.'], ['혼돈 중립', '자기 마음이 내키는 대로 행동하며 개인의 자유를 최우선으로 생각합니다.'],
  ['질서 악', '전통과 법, 질서에서 벗어나지 않는 한 자신의 욕망을 최우선으로 추구합니다.'], ['중립 악', '연민이나 후회 따위는 생각하지 않으며, 보복이나 처벌이 없을 것 같다면 무엇이든 원하는 대로 저지릅니다.'], ['혼돈 악', '탐욕, 증오, 피에 대한 갈망에 따라 무자비하게 폭력을 휘두르며 원하는 것을 차지합니다.'],
].map(([label, description]) => ({ id: label, label, description, details: ['성향은 도덕적 성향과 사회·질서 성향을 조합해 표현합니다.'] }))

type BlueprintProps = { sessionId: string; setupApi: { getPlayPreparation: NonNullable<SetupApi['getPlayPreparation']>; resolveBlueprint?: SetupApi['resolveBlueprint']; addBlueprintChild?: SetupApi['addBlueprintChild']; publishBlueprint?: SetupApi['publishBlueprint'] }; sessionApi: Pick<AdventureSessionApi, 'read'> }

function useBlueprintFields(blueprint?: BlueprintProps) {
  const [nodes, setNodes] = useState<ReturnType<typeof flattenNodes>>([])
  const [packageId, setPackageId] = useState<string | null>(null)
  const [revision, setRevision] = useState(0)
  const [values, setValues] = useState<Record<string, string>>({})
  useEffect(() => { if (!blueprint) return; let active = true; void blueprint.sessionApi.read(blueprint.sessionId).then(session => { if (!active) return; setPackageId(session.scenarioPackageId ?? null); return session.scenarioPackageId ? blueprint.setupApi.getPlayPreparation(session.scenarioPackageId) : null }).then(preparation => { if (active && preparation) { setRevision(preparation.characterCreationBlueprint.revision ?? 0); setNodes(flattenNodes(preparation.characterCreationBlueprint.roots)) } }); return () => { active = false } }, [blueprint])
  const mappedKeys = useMemo(() => new Set(['character_name', 'name', 'race', 'ancestry', 'species', 'character_class', 'class', 'background', 'alignment', 'level', 'strength', 'dexterity', 'constitution', 'intelligence', 'wisdom', 'charisma', 'str', 'dex', 'con', 'int', 'wis', 'cha']), [])
  const find = (keys: string[]) => nodes.find(node => keys.includes(node.key))
  const value = (keys: string[], fallback = '') => { const node = find(keys); return node ? values[node.id] ?? node.value ?? fallback : fallback }
  function change(keys: string[], next: string) { const node = find(keys); if (!node) return; setValues(current => ({ ...current, [node.id]: next })); if (packageId && blueprint?.setupApi.resolveBlueprint) void blueprint.setupApi.resolveBlueprint(packageId, node.id, next, revision).then(result => { if (typeof result === 'object' && result && 'revision' in result && typeof result.revision === 'number') setRevision(result.revision) }).catch(() => undefined) }
  const extras = nodes.filter(node => !mappedKeys.has(node.key))
  return { value, change, extras, values }
}

export function CharacterSheetCreatorView({ onSave, blueprint }: { onSave: (draft: Omit<CharacterCreationDraft, 'sessionId'>) => Promise<void>; blueprint?: BlueprintProps }) {
  const blueprintFields = useBlueprintFields(blueprint)
  const [name, setName] = useState('')
  const [characterClass, setCharacterClass] = useState('')
  const [subrace, setSubrace] = useState('')
  const [scores, setScores] = useState([0, 0, 0, 0, 0, 0])
  const [equipmentTab, setEquipmentTab] = useState<'owned' | 'carried'>('owned')
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  const mod = (value: number) => value ? `${value >= 10 ? '+' : ''}${Math.floor((value - 10) / 2)}` : '—'
  const field = (keys: string[], fallback = '') => blueprintFields.value(keys, fallback)
  const effectiveName = name || field(['character_name', 'name'])
  const effectiveClass = characterClass || field(['character_class', 'class'])
  const effectiveRace = field(['race', 'ancestry', 'species'])
  const effectiveSubrace = subrace || field(['subrace', 'subrace_name'])
  const effectiveBackground = field(['background'])
  const effectiveAlignment = field(['alignment'])
  const effectiveLevel = field(['level'], '1')
  const effectiveScores = scores.map((score, index) => score || Number(field(scoreKeys[index])))
  const activeArt = effectiveClass ? art[effectiveClass as keyof typeof art] : undefined
  async function save() { if (!effectiveName.trim() || !effectiveClass || effectiveScores.some(value => !value)) { setMessage('이름, 직업, 능력치를 먼저 입력하세요.'); return } setSaving(true); setMessage('저장 중입니다...'); try { await onSave({ edition: 'DND_5E_2014', characterName: effectiveName.trim(), level: Number(effectiveLevel) || 1, inspiration: false, race: effectiveRace || '하이 엘프', characterClass: effectiveClass, background: effectiveBackground || '학자', startingAbilities: effectiveScores.map((value, i) => `${scoreKeys[i][0]}=${value}`).join(','), characterBuild: JSON.stringify({ stats: effectiveScores, race: effectiveRace, subrace: effectiveSubrace, alignment: effectiveAlignment || '중립 선' }), characterState: JSON.stringify({ currentHitPoints: 0, temporaryHitPoints: 0, experience: 0 }) }); setMessage('캐릭터 시트를 저장했습니다.'); } catch (error) { setMessage(error instanceof Error ? error.message : '저장하지 못했습니다.'); } finally { setSaving(false) } }
  return <div className="sheet-creator"><aside className="creator-sidebar"><img className="creator-compass" src="/assets/characters/ui-icons/compass.png" alt="" /><h3>캐릭터 시트</h3>{[['basic','기본 정보'],['abilities','능력치'],['skills','기술'],['combat','전투'],['equipment','장비'],['book','주문'],['note','배경/성격'],['scroll','메모']].map(([icon, label]) => <a href={`#${icon}`} key={label}><img src={`/assets/characters/ui-icons/${icon}.png`} alt="" /><span>{label}</span></a>)}</aside><div className="sheet-creator-bar"><div><small>ADVENTURER'S ARCHIVE</small><h2>TRPG 캐릭터 생성</h2>{message && <p role="status">{message}</p>}</div><div><button className="sheet-light-button">불러오기</button><button className="sheet-light-button">내보내기</button><button className="sheet-save-button" onClick={() => void save()} disabled={saving}>▣ {saving ? '저장 중' : '저장'}</button></div></div><div className="sheet-creator-grid"><main>
    <section className="sheet-box"><SheetTitle n="1" title="기본 정보" /><div className="sheet-fields"><label>캐릭터 이름<input placeholder="이름을 입력하세요" value={effectiveName} onChange={e => { setName(e.target.value); blueprintFields.change(['character_name', 'name'], e.target.value) }} /></label><ChoiceField label="종족" value={effectiveRace} options={raceChoices} onChange={value => { setSubrace(''); blueprintFields.change(['race', 'ancestry', 'species'], value); blueprintFields.change(['subrace', 'subrace_name'], '') }} /><ChoiceField label="하위 종족" value={effectiveSubrace} options={subraceChoicesFor(effectiveRace)} disabled={!effectiveRace || subraceChoicesFor(effectiveRace).length === 0} onChange={value => { setSubrace(value); blueprintFields.change(['subrace', 'subrace_name'], value) }} /><ChoiceField label="직업" value={effectiveClass} options={classChoices} onChange={value => { setCharacterClass(value); blueprintFields.change(['character_class', 'class'], value) }} /><label>레벨<input type="number" value={effectiveLevel} onChange={e => blueprintFields.change(['level'], e.target.value)} min="1" /></label><ChoiceField label="배경" value={effectiveBackground} options={backgroundChoices} onChange={value => blueprintFields.change(['background'], value)} /><ChoiceField label="성향" value={effectiveAlignment} options={alignmentChoices} onChange={value => blueprintFields.change(['alignment'], value)} /></div><BlueprintExtras nodes={blueprintFields.extras} values={blueprintFields.values} onChange={(node, value) => blueprintFields.change([node.key], value)} /></section>
    <section className="sheet-box"><SheetTitle n="2" title="능력치" /><div className="sheet-abilities">{stats.map((stat, i) => <AbilityCard key={stat} stat={stat} index={i} value={effectiveScores[i] || 0} modifier={mod(effectiveScores[i])} onChange={value => { setScores(old => old.map((v, j) => j === i ? value : v)); blueprintFields.change(scoreKeys[i], String(value)) }} />)}</div></section>
    <section className="sheet-box"><SheetTitle n="3" title="보조 능력치" /><div className="sheet-metrics"><Metric l="♥ HP" v="32 / 32" /><Metric l="◈ AC" v="15" /><Metric l="♟ 이동속도" v="9m" /><Metric l="★ 숙련 보너스" v="+3" /><Metric l="⚔ 주도권" v="+2" /></div></section>
    <div className="sheet-columns"><SheetTable n="4" title="기술" items={['운동 (Athletics)', '은신 (Stealth)', '지각 (Perception)', '설득 (Persuasion)', '비전 (Arcana)', '생존 (Survival)']} /><EquipmentPanel tab={equipmentTab} onTabChange={setEquipmentTab} /><SpellPanel /></div>
    <section className="sheet-box"><SheetTitle n="7" title="배경 / 성격" /><div className="sheet-fields sheet-personality">{['성격 특성', '이상', '유대', '결점'].map((label, i) => <label key={label}>{label}<input defaultValue={['지식을 얻는 것을 무엇보다 즐긴다.', '진실은 언젠가 밝혀져야 한다.', '스승의 가르침을 널리 전하고 싶다.', '때때로 오만하고 타인을 무시한다.'][i]} /></label>)}</div><label>추가 메모<textarea defaultValue="고대 유적지로 잃어버린 언어에 관심이 많다. 마법 연구를 위해 여정을 떠났다." /></label></section>
    </main><aside className="sheet-preview"><h3>미리보기</h3><div className="sheet-parchment">{activeArt ? <img src={activeArt} alt={`${effectiveClass} 일러스트`} /> : <div className="sheet-empty-portrait">캐릭터 일러스트</div>}<h2>{effectiveName || '이름 없는 모험가'}</h2><h4>{effectiveClass ? `${effectiveClass} · 레벨 ${effectiveLevel}` : '직업과 레벨'}</h4><p>{effectiveRace || '종족을 선택하세요'}</p><p>{effectiveBackground || '배경을 선택하세요'}</p><p>{effectiveAlignment || '성향을 선택하세요'}</p><div className="sheet-metrics"><Metric l="♥ HP" v={effectiveScores.some(Boolean) ? '— / —' : '—'} /><Metric l="◈ AC" v="—" /><Metric l="⚔ 주도권" v="—" /></div><h5>능력치</h5><div className="sheet-preview-stats">{stats.map((stat, i) => <div key={stat}><span>{stat}</span><b>{effectiveScores[i] || '—'}</b><small>{mod(effectiveScores[i])}</small></div>)}</div><h5>기술 (숙련된 표시)</h5><p>캐릭터 정보를 입력하면 표시됩니다.</p><button className="sheet-save-button" onClick={() => void save()} disabled={saving}>{saving ? '저장 중...' : '캐릭터 저장하기 →'}</button></div></aside></div></div>
}
function ChoiceField({ label, value, options, onChange, disabled = false }: { label: string; value: string; options: ChoiceOption[]; onChange: (value: string) => void; disabled?: boolean }) { const [open, setOpen] = useState(false); return <label className="choice-field">{label}<button type="button" className="sheet-choice-button" disabled={disabled} onClick={() => setOpen(true)}>{options.find(option => option.id === value)?.label || value || (disabled ? '상위 종족을 먼저 선택하세요' : '선택하세요')}<span>⌄</span></button>{open && <ChoicePicker title={`${label} 선택`} options={options} selected={value} onClose={() => setOpen(false)} onChange={next => { onChange(next); setOpen(false) }} />}</label> }
function ChoicePicker({ title, options, selected, onClose, onChange }: { title: string; options: ChoiceOption[]; selected: string; onClose: () => void; onChange: (value: string) => void }) { return <div className="choice-picker-backdrop" role="presentation" onMouseDown={event => { if (event.currentTarget === event.target) onClose() }}><section className="choice-picker" role="dialog" aria-modal="true" aria-label={title}><div className="choice-picker-head"><div><small>D&amp;D 5TH · PLAYER'S HANDBOOK</small><h2>{title}</h2></div><button type="button" aria-label="선택 창 닫기" onClick={onClose}>×</button></div><div className="choice-picker-grid">{options.map(option => <button type="button" key={option.id} className={selected === option.id ? 'selected' : ''} onClick={() => onChange(option.id)}><strong>{option.label}</strong><p>{option.description}</p><small>{option.details.join(' · ')}</small></button>)}</div></section></div> }
function AbilityCard({ stat, index, value, modifier, onChange }: { stat: string; index: number; value: number; modifier: string; onChange: (value: number) => void }) { const icons = ['fist', 'sword', 'heart', 'book', 'staff', 'star']; const colors = ['red', 'green', 'gold', 'blue', 'violet', 'magenta']; return <div className={`sheet-ability sheet-ability-${colors[index]}`}><div className="ability-name"><img src={`/assets/characters/icons/${icons[index]}.png`} alt="" /><b>{stat}</b></div><div className="ability-value"><input type="number" placeholder="—" value={value || ''} onChange={event => onChange(Number(event.target.value))} /><strong>{modifier}</strong></div></div> }
function EquipmentPanel({ tab, onTabChange }: { tab: 'owned' | 'carried'; onTabChange: (tab: 'owned' | 'carried') => void }) { const items = tab === 'owned' ? [['단검', '무기', '1 kg'], ['지팡이', '무기', '2 kg'], ['가죽 갑옷', '방어구', '5 kg'], ['배낭', '기타', '2 kg'], ['노트북', '기타', '1 kg']] : [['퀴터스태프 또는 단검', '근접 무기', ''], ['구성품 및 식별', '도구', ''], ['마법책 포함', '주문 기록', '']]; return <section className="sheet-box equipment-panel"><SheetTitle n="5" title="장비" /><div className="equipment-tabs"><button className={tab === 'owned' ? 'active' : ''} onClick={() => onTabChange('owned')}>보유 장비</button><button className={tab === 'carried' ? 'active' : ''} onClick={() => onTabChange('carried')}>휴대 장비 물품</button></div><div className="equipment-list">{items.map(([name, type, weight]) => <div key={name}><span>{name}<small>{type}</small></span><em>{weight}</em><button aria-label={`${name} 편집`}>✎</button><button aria-label={`${name} 삭제`}>♧</button></div>)}</div><div className="equipment-total">총 무게&nbsp; 11 / 120 kg</div><button className="sheet-add">＋ 장비 추가</button></section> }
function SpellPanel() { const [open, setOpen] = useState(false); const [selected, setSelected] = useState<string[]>([]); return <section className="sheet-box spell-panel"><SheetTitle n="6" title="주문" /><div className="spell-summary"><label>주문 시전 능력<select defaultValue="지능"><option>지능</option><option>지혜</option><option>매력</option></select></label><label>주문 DC<input value="14" readOnly /></label><label>주문 공격 보너스<input value="+6" readOnly /></label></div><div className="spell-list">{(selected.length ? selected : ['매직 미사일', '보호막', '미러리 이미지', '미스틱 스텝']).map((spell, index) => <div key={spell}><span>{spell}</span><em>{index + 1}</em><small>{index < 2 ? '1 행동' : '1 반응'}</small><input type="checkbox" defaultChecked={index < 2} /></div>)}</div><button className="sheet-add" onClick={() => setOpen(true)}>＋ 주문 선택</button>{open && <SpellPicker selected={selected} onClose={() => setOpen(false)} onChange={setSelected} />}</section> }
function SpellPicker({ selected, onClose, onChange }: { selected: string[]; onClose: () => void; onChange: (value: string[]) => void }) { const spells = ['매직 미사일', '보호막', '마법 갑옷', '미러리 이미지', '안개 걸음', '미스틱 스텝', '카운터스펠', '불타는 광선']; return <div className="spell-picker-backdrop" role="presentation" onMouseDown={event => { if (event.currentTarget === event.target) onClose() }}><section className="spell-picker" role="dialog" aria-modal="true" aria-labelledby="spell-picker-title"><div className="spell-picker-head"><div><small>주문 목록</small><h2 id="spell-picker-title">사용할 주문 선택</h2></div><button aria-label="주문 선택 닫기" onClick={onClose}>×</button></div><div className="spell-picker-grid">{spells.map(spell => <label key={spell} className={selected.includes(spell) ? 'selected' : ''}><input type="checkbox" checked={selected.includes(spell)} onChange={event => onChange(event.target.checked ? [...selected, spell] : selected.filter(item => item !== spell))} /><span>{spell}</span><small>1레벨 · 기본 주문</small></label>)}</div><button className="sheet-save-button" onClick={onClose}>선택 적용</button></section></div> }
function SheetTitle({ n, title }: { n: string; title: string }) { return <div className="sheet-title"><img src="/assets/characters/icons/star.png" alt="" /><h3>{n}. {title}</h3></div> }
function Metric({ l, v }: { l: string; v: string }) { const icon = l.startsWith('♥') ? 'heart' : l.startsWith('◈') ? 'shield' : l.startsWith('♟') ? 'boots' : l.startsWith('★') ? 'star' : 'crossed-swords'; return <div className="sheet-metric"><span><img className="sheet-icon-image" src={`/assets/characters/icons/${icon}.png`} alt="" />{l.slice(1)}</span><b>{v}</b></div> }
function SheetTable({ n, title, items }: { n: string; title: string; items: string[] }) { return <section className="sheet-box"><SheetTitle n={n} title={title} /><div className="sheet-table">{items.map((item, i) => <div key={item}><span>{item}</span><em>{i % 2 ? '민첩' : '지능'}</em><input type="checkbox" defaultChecked={i === 1 || i === 2} /><b>+{i + 1}</b></div>)}</div><button className="sheet-add">＋ {title} 추가</button></section> }
function BlueprintExtras({ nodes, values, onChange }: { nodes: CharacterInputNodeView[]; values: Record<string, string>; onChange: (node: CharacterInputNodeView, value: string) => void }) { if (!nodes.length) return null; return <div className="blueprint-inline-fields">{nodes.map(node => { const value = values[node.id] ?? node.value ?? ''; return <label key={node.id}>{node.label}{node.inputMode === 'SINGLE_SELECT' ? <select value={value} onChange={event => onChange(node, event.target.value)}><option value="">선택하세요</option>{node.options.map(option => <option key={option}>{option}</option>)}</select> : node.inputMode === 'MULTI_SELECT' ? <select multiple value={value.split(',').filter(Boolean)} onChange={event => onChange(node, Array.from(event.target.selectedOptions, option => option.value).join(','))}>{node.options.map(option => <option key={option}>{option}</option>)}</select> : <input value={value} onChange={event => onChange(node, event.target.value)} />}</label> })}</div> }

function flattenNodes(nodes: Awaited<ReturnType<NonNullable<SetupApi['getPlayPreparation']>>>['characterCreationBlueprint']['roots']): NonNullable<typeof nodes>[number][] { return (nodes ?? []).flatMap(node => [node, ...flattenNodes(node.children)]) }
