
import { useEffect, useMemo, useState } from 'react'
import type { CharacterCreationDraft, CharacterInputNodeView, SetupApi } from '../rulebooks/SetupApi'
import type { AdventureSessionApi } from '../adventure-session/AdventureSessionApi'

const stats = ['근력', '민첩', '건강', '지능', '지혜', '매력']
const scoreKeys = [['strength', 'str'], ['dexterity', 'dex'], ['constitution', 'con'], ['intelligence', 'int'], ['wisdom', 'wis'], ['charisma', 'cha']]
const art = { 위저드: '/assets/characters/wizard.png', 팔라딘: '/assets/characters/paladin.png', 로그: '/assets/characters/rogue.png' }

type BlueprintProps = { sessionId: string; setupApi: { getPlayPreparation: NonNullable<SetupApi['getPlayPreparation']>; resolveBlueprint?: SetupApi['resolveBlueprint']; addBlueprintChild?: SetupApi['addBlueprintChild']; publishBlueprint?: SetupApi['publishBlueprint'] }; sessionApi: Pick<AdventureSessionApi, 'read'> }

function useBlueprintFields(blueprint?: BlueprintProps) {
  const [nodes, setNodes] = useState<ReturnType<typeof flattenNodes>>([])
  const [packageId, setPackageId] = useState<string | null>(null)
  const [revision, setRevision] = useState(0)
  const [values, setValues] = useState<Record<string, string>>({})
  useEffect(() => { if (!blueprint) return; let active = true; void blueprint.sessionApi.read(blueprint.sessionId).then(session => { if (!active) return; setPackageId(session.scenarioPackageId ?? null); return session.scenarioPackageId ? blueprint.setupApi.getPlayPreparation(session.scenarioPackageId) : null }).then(preparation => { if (active && preparation) { setRevision(preparation.characterCreationBlueprint.revision ?? 0); setNodes(flattenNodes(preparation.characterCreationBlueprint.roots)) } }); return () => { active = false } }, [blueprint])
  const mappedKeys = useMemo(() => new Set(['character_name', 'name', 'race', 'ancestry', 'species', 'character_class', 'class', 'background', 'alignment', 'level', 'strength', 'dexterity', 'constitution', 'intelligence', 'wisdom', 'charisma', 'str', 'dex', 'con', 'int', 'wis', 'cha']), [])
  const find = (keys: string[]) => nodes.find(node => keys.includes(node.key))
  const value = (keys: string[], fallback = '') => { const node = find(keys); return node ? values[node.id] ?? node.value ?? fallback : fallback }
  function change(keys: string[], next: string) { const node = find(keys); if (!node) return; setValues(current => ({ ...current, [node.id]: next })); if (packageId && blueprint?.setupApi.resolveBlueprint) void blueprint.setupApi.resolveBlueprint(packageId, node.id, next, revision).then(result => { if (typeof result === 'object' && result && 'revision' in result && typeof result.revision === 'number') setRevision(result.revision) }).catch(() => undefined) }
  const extras = nodes.filter(node => !mappedKeys.has(node.key))
  return { value, change, extras, values }
}

export function CharacterSheetCreatorView({ onSave, blueprint }: { onSave: (draft: Omit<CharacterCreationDraft, 'sessionId'>) => Promise<void>; blueprint?: BlueprintProps }) {
  const blueprintFields = useBlueprintFields(blueprint)
  const [name, setName] = useState('')
  const [characterClass, setCharacterClass] = useState('')
  const [scores, setScores] = useState([0, 0, 0, 0, 0, 0])
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  const mod = (value: number) => value ? `${value >= 10 ? '+' : ''}${Math.floor((value - 10) / 2)}` : '—'
  const field = (keys: string[], fallback = '') => blueprintFields.value(keys, fallback)
  const effectiveName = name || field(['character_name', 'name'])
  const effectiveClass = characterClass || field(['character_class', 'class'])
  const effectiveRace = field(['race', 'ancestry', 'species'])
  const effectiveBackground = field(['background'])
  const effectiveAlignment = field(['alignment'])
  const effectiveLevel = field(['level'], '1')
  const effectiveScores = scores.map((score, index) => score || Number(field(scoreKeys[index])))
  const activeArt = effectiveClass ? art[effectiveClass as keyof typeof art] : undefined
  async function save() { if (!effectiveName.trim() || !effectiveClass || effectiveScores.some(value => !value)) { setMessage('이름, 직업, 능력치를 먼저 입력하세요.'); return } setSaving(true); setMessage('저장 중입니다...'); try { await onSave({ edition: 'DND_5E_2014', characterName: effectiveName.trim(), level: Number(effectiveLevel) || 1, inspiration: false, race: effectiveRace || '하이 엘프', characterClass: effectiveClass, background: effectiveBackground || '학자', startingAbilities: effectiveScores.map((value, i) => `${scoreKeys[i][0]}=${value}`).join(','), characterBuild: JSON.stringify({ stats: effectiveScores, alignment: effectiveAlignment || '중립 선' }), characterState: JSON.stringify({ currentHitPoints: 0, temporaryHitPoints: 0, experience: 0 }) }); setMessage('캐릭터 시트를 저장했습니다.'); } catch (error) { setMessage(error instanceof Error ? error.message : '저장하지 못했습니다.'); } finally { setSaving(false) } }
  return <div className="sheet-creator"><aside className="creator-sidebar"><img className="creator-compass" src="/assets/characters/ui-icons/compass.png" alt="" /><h3>캐릭터 시트</h3>{[['basic','기본 정보'],['abilities','능력치'],['skills','기술'],['combat','전투'],['equipment','장비'],['book','주문'],['note','배경/성격'],['scroll','메모']].map(([icon, label]) => <a href={`#${icon}`} key={label}><img src={`/assets/characters/ui-icons/${icon}.png`} alt="" /><span>{label}</span></a>)}</aside><div className="sheet-creator-bar"><div><small>ADVENTURER'S ARCHIVE</small><h2>TRPG 캐릭터 생성</h2>{message && <p role="status">{message}</p>}</div><div><button className="sheet-light-button">불러오기</button><button className="sheet-light-button">내보내기</button><button className="sheet-save-button" onClick={() => void save()} disabled={saving}>▣ {saving ? '저장 중' : '저장'}</button></div></div><div className="sheet-creator-grid"><main>
    <section className="sheet-box"><SheetTitle n="1" title="기본 정보" /><div className="sheet-fields"><label>캐릭터 이름<input placeholder="이름을 입력하세요" value={effectiveName} onChange={e => { setName(e.target.value); blueprintFields.change(['character_name', 'name'], e.target.value) }} /></label><label>종족<select value={effectiveRace} onChange={e => blueprintFields.change(['race', 'ancestry', 'species'], e.target.value)}><option value="">선택하세요</option><option>하이 엘프</option><option>인간</option><option>하프 엘프</option></select></label><label>직업<select value={effectiveClass} onChange={e => { setCharacterClass(e.target.value); blueprintFields.change(['character_class', 'class'], e.target.value) }}><option value="">선택하세요</option>{effectiveClass && !Object.keys(art).includes(effectiveClass) && <option>{effectiveClass}</option>}{Object.keys(art).map(item => <option key={item}>{item}</option>)}</select></label><label>레벨<input type="number" value={effectiveLevel} onChange={e => blueprintFields.change(['level'], e.target.value)} min="1" /></label><label>배경<select value={effectiveBackground} onChange={e => blueprintFields.change(['background'], e.target.value)}><option value="">선택하세요</option><option>학자</option><option>수호자</option><option>도적</option></select></label><label>성향<select value={effectiveAlignment} onChange={e => blueprintFields.change(['alignment'], e.target.value)}><option value="">선택하세요</option><option>중립 선</option><option>질서 선</option><option>혼돈 중립</option></select></label><label>플레이어<input placeholder="플레이어 이름" /></label></div><BlueprintExtras nodes={blueprintFields.extras} values={blueprintFields.values} onChange={(node, value) => blueprintFields.change([node.key], value)} /></section>
    <section className="sheet-box"><SheetTitle n="2" title="능력치" /><div className="sheet-abilities">{stats.map((stat, i) => { const value = effectiveScores[i] || ''; return <div className="sheet-ability" key={stat}><b>{stat}</b><input type="number" placeholder="—" value={value} onChange={e => { const next = Number(e.target.value); setScores(old => old.map((v, j) => j === i ? next : v)); blueprintFields.change(scoreKeys[i], e.target.value) }} /><strong>{mod(Number(value))}</strong></div> })}</div></section>
    <section className="sheet-box"><SheetTitle n="3" title="보조 능력치" /><div className="sheet-metrics"><Metric l="♥ HP" v="32 / 32" /><Metric l="◈ AC" v="15" /><Metric l="♟ 이동속도" v="9m" /><Metric l="★ 숙련 보너스" v="+3" /><Metric l="⚔ 주도권" v="+2" /></div></section>
    <div className="sheet-columns"><SheetTable n="4" title="기술" items={['운동 (Athletics)', '은신 (Stealth)', '지각 (Perception)', '설득 (Persuasion)', '비전 (Arcana)', '생존 (Survival)']} /><SheetTable n="5" title="장비" items={['퀴터스태프 또는 단검', '구성품 및 식별', '마법책 포함', '여행자 배낭']} /><SheetTable n="6" title="주문" items={['매직 미사일', '보호막', '미러리 이미지', '미스틱 스텝']} /></div>
    <section className="sheet-box"><SheetTitle n="7" title="배경 / 성격" /><div className="sheet-fields sheet-personality">{['성격 특성', '이상', '유대', '결점'].map((label, i) => <label key={label}>{label}<input defaultValue={['지식을 얻는 것을 무엇보다 즐긴다.', '진실은 언젠가 밝혀져야 한다.', '스승의 가르침을 널리 전하고 싶다.', '때때로 오만하고 타인을 무시한다.'][i]} /></label>)}</div><label>추가 메모<textarea defaultValue="고대 유적지로 잃어버린 언어에 관심이 많다. 마법 연구를 위해 여정을 떠났다." /></label></section>
</main><aside className="sheet-preview"><h3>미리보기</h3><div className="sheet-parchment">{activeArt ? <img src={activeArt} alt={`${characterClass} 일러스트`} /> : <div className="sheet-empty-portrait">캐릭터 일러스트</div>}<h2>{name || '이름 없는 모험가'}</h2><h4>{characterClass ? `${characterClass} · 레벨 1` : '직업과 레벨'}</h4><p>{characterClass ? '하이 엘프' : '종족을 선택하세요'}</p><p>{characterClass ? '학자' : '배경을 선택하세요'}</p><p>{characterClass ? '중립 선' : '성향을 선택하세요'}</p><div className="sheet-metrics"><Metric l="♥ HP" v={scores.some(Boolean) ? '— / —' : '—'} /><Metric l="◈ AC" v="—" /><Metric l="⚔ 주도권" v="—" /></div><h5>능력치</h5><div className="sheet-preview-stats">{stats.map((stat, i) => <div key={stat}><span>{stat}</span><b>{scores[i] || '—'}</b><small>{mod(scores[i])}</small></div>)}</div><h5>기술 (숙련된 표시)</h5><p>캐릭터 정보를 입력하면 표시됩니다.</p><button className="sheet-save-button" onClick={() => void save()} disabled={saving}>{saving ? '저장 중...' : '캐릭터 저장하기 →'}</button></div></aside></div></div>
}
function SheetTitle({ n, title }: { n: string; title: string }) { return <div className="sheet-title"><img src="/assets/characters/icons/star.png" alt="" /><h3>{n}. {title}</h3></div> }
function Metric({ l, v }: { l: string; v: string }) { const icon = l.startsWith('♥') ? 'heart' : l.startsWith('◈') ? 'shield' : l.startsWith('♟') ? 'boots' : l.startsWith('★') ? 'star' : 'crossed-swords'; return <div className="sheet-metric"><span><img className="sheet-icon-image" src={`/assets/characters/icons/${icon}.png`} alt="" />{l.slice(1)}</span><b>{v}</b></div> }
function SheetTable({ n, title, items }: { n: string; title: string; items: string[] }) { return <section className="sheet-box"><SheetTitle n={n} title={title} /><div className="sheet-table">{items.map((item, i) => <div key={item}><span>{item}</span><em>{i % 2 ? '민첩' : '지능'}</em><input type="checkbox" defaultChecked={i === 1 || i === 2} /><b>+{i + 1}</b></div>)}</div><button className="sheet-add">＋ {title} 추가</button></section> }
function BlueprintExtras({ nodes, values, onChange }: { nodes: CharacterInputNodeView[]; values: Record<string, string>; onChange: (node: CharacterInputNodeView, value: string) => void }) { if (!nodes.length) return null; return <div className="blueprint-inline-fields">{nodes.map(node => { const value = values[node.id] ?? node.value ?? ''; return <label key={node.id}>{node.label}{node.inputMode === 'SINGLE_SELECT' ? <select value={value} onChange={event => onChange(node, event.target.value)}><option value="">선택하세요</option>{node.options.map(option => <option key={option}>{option}</option>)}</select> : node.inputMode === 'MULTI_SELECT' ? <select multiple value={value.split(',').filter(Boolean)} onChange={event => onChange(node, Array.from(event.target.selectedOptions, option => option.value).join(','))}>{node.options.map(option => <option key={option}>{option}</option>)}</select> : <input value={value} onChange={event => onChange(node, event.target.value)} />}</label> })}</div> }

function flattenNodes(nodes: Awaited<ReturnType<NonNullable<SetupApi['getPlayPreparation']>>>['characterCreationBlueprint']['roots']): NonNullable<typeof nodes>[number][] { return (nodes ?? []).flatMap(node => [node, ...flattenNodes(node.children)]) }
