package com.dndmaster.aigamemaster.infrastructure.ai;
import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;import java.util.concurrent.ConcurrentHashMap;import org.springframework.ai.chat.model.*;import org.springframework.ai.chat.prompt.Prompt;import reactor.core.publisher.Flux;
public final class SpringAiChatAdapter{
 private final ChatModel model;private final int maxAttempts;private final SafeAiAuditLogger logger;private final Map<String,CachedResult> completed=new ConcurrentHashMap<>();private final Map<String,String> fingerprints=new ConcurrentHashMap<>();
 public SpringAiChatAdapter(ChatModel model,int maxAttempts,SafeAiAuditLogger logger){this.model=Objects.requireNonNull(model);if(maxAttempts<1)throw new IllegalArgumentException("max attempts positive");this.maxAttempts=maxAttempts;this.logger=Objects.requireNonNull(logger);}
 public <T>T complete(String operationId,String prompt,StructuredResponseParser<T> parser){String fingerprint=register(operationId,prompt);CachedResult cached=completed.get(operationId);if(cached!=null)return cast(cached.value);for(int attempt=1;;attempt++){try{ChatResponse response=model.call(new Prompt(prompt));String text=text(response);T parsed=parser.parse(text);completed.put(operationId,new CachedResult(fingerprint,parsed));logger.success(operationId);return parsed;}catch(ProviderMalformedResponseException e){logger.failure(operationId,e);throw e;}catch(RuntimeException e){RuntimeException mapped=SpringAiProviderExceptionMapper.map(e);if(!retryable(mapped)||attempt>=maxAttempts){logger.failure(operationId,mapped);throw mapped;}}}}
 public Flux<String> stream(String operationId,String prompt){String fingerprint=register(operationId,prompt);CachedResult cached=completed.get(operationId);if(cached!=null){@SuppressWarnings("unchecked")List<String> chunks=(List<String>)cached.value;return Flux.fromIterable(chunks);}return Flux.defer(()->{List<String> chunks=new ArrayList<>();return model.stream(new Prompt(prompt)).map(SpringAiChatAdapter::text).doOnNext(chunks::add).doOnComplete(()->{completed.put(operationId,new CachedResult(fingerprint,List.copyOf(chunks)));logger.success(operationId);}).doOnError(e->logger.failure(operationId,e));});}
 private String register(String id,String prompt){if(id==null||id.isBlank()||prompt==null||prompt.isBlank())throw new IllegalArgumentException("operation id and prompt required");String hash=hash(prompt);String previous=fingerprints.putIfAbsent(id,hash);if(previous!=null&&!previous.equals(hash))throw new AiOperationConflictException();return hash;}
 private static boolean retryable(Throwable e){return e instanceof ProviderTimeoutException||e instanceof ProviderRateLimitException;}
 private static String text(ChatResponse response){if(response==null||response.getResult()==null||response.getResult().getOutput()==null||response.getResult().getOutput().getText()==null||response.getResult().getOutput().getText().isBlank())throw new ProviderMalformedResponseException("AI response missing text");return response.getResult().getOutput().getText();}
 private static String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 @SuppressWarnings("unchecked")private static<T>T cast(Object value){return(T)value;}private record CachedResult(String fingerprint,Object value){}
}
